### ISSUE TITLE
Convert events to use a meta field instead of publish date

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBMC_TH_MMHC#3]
The current system for events in this theme looks for events with the `future` status which is a little odd. It creates a confusing content management experience for these folks and also makes the archives not show events once the date is passed. I'd like us to either completely replace that post type with something better or manipulate it so that it works more intuitively.

**Comment by d4mation** [comment]
This issue was moved to realbig/RBM_TH_MHCC#2
